### ISSUE TITLE
Fails on a mac machine

### ISSUE THREAD

**Issue by rgksugan** [cosme12/cheatsheet-maker#22]
```
Traceback (most recent call last):
  File "sheetmaker/sheetmaker.py", line 14, in <module>
    import sheet_wizard
  File "/Users/gsuga/Play/cheatsheet-maker/sheetmaker/sheet_wizard.py", line 68
SyntaxError: Non-ASCII character '\xc3' in file /Users/gsuga/Play/cheatsheet-maker/sheetmaker/sheet_wizard.py on line 68, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

This happens in MAC machine.

**Comment by cosme12** [comment]
Hey, that error is due to the "Ñ" character used in spanish. To fix it:
- go to line 68 of ``` sheetwizard.py ``` and remove that character
- I think using python 3+ fix it automatically
- add this to the top of the file if you are using python 2.7

 ``` 
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```

Try those and see if any of them work.

**Comment by rgksugan** [comment]
Hi @cosme12,

It fixed it. Thanks for responding.

Facing a different issue now. On selecting an option from the menu it still keep on going in a loop.

```
Choose your language:
1. English
2. Español
1
Choose your language:
1. English
2. Español
1
Choose your language:
1. English
2. Español
2
Choose your language:
1. English
2. Español
1
```
